version: '2.0'

services:
  ui:
    build: .
    ports:
      - "3000:80"
    env_file:
      - ./.env
    environment:
      HOST: "0.0.0.0"
      PORT: "80"

  node:
    image: node:18-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh
